apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: gegham
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
      nodePort: 30007
  type: NodePort
