apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu-pod
spec:
  containers:
  - name: mybackend
    image: ubuntu:latest
    volumeMounts:
    - mountPath: "/var/www/html"
      name: mypd
  volumes:
    - name: mypd 
      persistentVolumeClaim:
        claimName: my-pvc