apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: gegham
spec:
  selector:
   app: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
